# frozen_string_literal: true

require "json"
require "net/http"
require "time"
require "uri"
require "fileutils"
require "voting_wizard"

require_relative "voting_bot/config"
require_relative "voting_bot/errors"
require_relative "voting_bot/application"
require_relative "voting_bot/update_loop"
require_relative "voting_bot/telegram_client"
require_relative "voting_bot/message_router"
require_relative "voting_bot/responder"
require_relative "voting_bot/state_context"
require_relative "voting_bot/models/session"
require_relative "voting_bot/models/update"
require_relative "voting_bot/models/poll_record"
require_relative "voting_bot/persistence/json_store"
require_relative "voting_bot/states/base"
require_relative "voting_bot/states/idle"
require_relative "voting_bot/states/awaiting_question"
require_relative "voting_bot/states/awaiting_options"
require_relative "voting_bot/states/awaiting_poll_settings"
require_relative "voting_bot/states/awaiting_correct_answers"
require_relative "voting_bot/states/awaiting_deadline"
require_relative "voting_bot/states/awaiting_vote_choice"
require_relative "voting_bot/states/factory"
